from PyQt5.QtWidgets import (
    QWidget, QPushButton, QHBoxLayout, QVBoxLayout,
    QLabel, QSlider, QStyle, QStackedWidget
)

from PyQt5.QtCore import Qt, QSize
from crop_widgets import DrawWidget

class Ui_CropApp:
    def setupUi(self, CropAppWindow):
        CropAppWindow.setWindowTitle(CropAppWindow.base_title)
        CropAppWindow.view_stack = QStackedWidget(CropAppWindow)
        CropAppWindow.video_frame = QWidget(CropAppWindow)
        CropAppWindow.video_frame.setStyleSheet("background-color: black;")
        CropAppWindow.video_frame.setFocusPolicy(Qt.StrongFocus)
        CropAppWindow.draw_widget = DrawWidget(CropAppWindow)
        CropAppWindow.view_stack.addWidget(CropAppWindow.video_frame)
        CropAppWindow.view_stack.addWidget(CropAppWindow.draw_widget)
        CropAppWindow.play_pause_button = QPushButton("Play")
        CropAppWindow.play_pause_button.setEnabled(False)
        CropAppWindow.play_pause_button.setIcon(CropAppWindow.style().standardIcon(QStyle.SP_MediaPlay))
        CropAppWindow.open_button = QPushButton("Open File")
        CropAppWindow.snapshot_button = QPushButton("Begin Crops")
        CropAppWindow.snapshot_button.setEnabled(False)
        CropAppWindow.back_button = QPushButton("Back to Video")
        CropAppWindow.send_crop_button = QPushButton("Send to Portrait")
        CropAppWindow.send_crop_button.setVisible(False)
        CropAppWindow.reset_state_button = QPushButton("Reset State")
        CropAppWindow.reset_state_button.setStyleSheet("background-color: #D96A6A;")
        CropAppWindow.position_slider = QSlider(Qt.Horizontal)
        CropAppWindow.position_slider.setRange(0, 1000)
        CropAppWindow.position_slider.setEnabled(False)
        CropAppWindow.coordinates_label = QLabel("Crop coordinates will be shown here")
        CropAppWindow.coordinates_label.setAlignment(Qt.AlignCenter)
        control_layout = QHBoxLayout()
        control_layout.setSpacing(20)
        control_layout.addStretch()
        control_layout.addWidget(CropAppWindow.open_button)
        control_layout.addWidget(CropAppWindow.play_pause_button)
        control_layout.addWidget(CropAppWindow.snapshot_button)
        control_layout.addWidget(CropAppWindow.back_button)
        control_layout.addWidget(CropAppWindow.send_crop_button)
        control_layout.addStretch()
        control_layout.addWidget(CropAppWindow.reset_state_button)
        button_size = QSize(160, 40)
        CropAppWindow.open_button.setFixedSize(button_size)
        CropAppWindow.play_pause_button.setFixedSize(button_size)
        CropAppWindow.snapshot_button.setFixedSize(button_size)
        CropAppWindow.back_button.setFixedSize(button_size)
        CropAppWindow.send_crop_button.setFixedSize(button_size)
        CropAppWindow.reset_state_button.setFixedSize(button_size)
        vbox = QVBoxLayout()
        vbox.addWidget(CropAppWindow.view_stack, 1)
        vbox.addWidget(CropAppWindow.position_slider)
        vbox.addLayout(control_layout)
        vbox.addWidget(CropAppWindow.coordinates_label)
        CropAppWindow.setLayout(vbox)
