from PyQt5.QtGui import QColor
from PyQt5.QtWidgets import (
    QWidget, QPushButton, QHBoxLayout, QVBoxLayout,
    QLabel, QSlider, QStackedWidget, QFrame, QProgressBar, QScrollArea, QSplitter, QCheckBox, QGraphicsScene
)

from PyQt5.QtCore import Qt
from crop_widgets import DrawWidget
from config import HUD_ELEMENT_MAPPINGS, UNIFIED_STYLESHEET, UI_LAYOUT, UI_COLORS
from portrait_view import PortraitView

class Ui_CropApp:
    def setupUi(self, CropAppWindow):
        CropAppWindow.setWindowTitle("Fortnite Crop Tool")
        CropAppWindow.resize(1800, 900)
        main_layout = QHBoxLayout(CropAppWindow)
        main_layout.setContentsMargins(0, 0, 0, 0)
        main_layout.setSpacing(0)
        splitter = QSplitter(Qt.Horizontal)
        main_layout.addWidget(splitter)
        left_pane_widget = QFrame()
        left_pane_layout = QVBoxLayout(left_pane_widget)
        left_pane_layout.setContentsMargins(0, 0, 0, 0)
        left_pane_layout.setSpacing(0)
        CropAppWindow.wizard_frame = QFrame()
        CropAppWindow.wizard_frame.setObjectName("wizardFrame")
        left_pane_layout.addWidget(CropAppWindow.wizard_frame)
        wizard_layout = QVBoxLayout(CropAppWindow.wizard_frame)
        wizard_layout.setContentsMargins(20, 15, 20, 15)
        wizard_layout.setSpacing(10)
        progress_frame = QFrame()
        progress_frame.setObjectName("progressFrame")
        wizard_layout.addWidget(progress_frame)
        progress_layout = QHBoxLayout(progress_frame)
        progress_layout.setSpacing(15)
        CropAppWindow.hud_elements = list(HUD_ELEMENT_MAPPINGS.values())
        CropAppWindow.progress_labels = {}
        for i, element in enumerate(CropAppWindow.hud_elements):
            label = QLabel(element.upper())
            label.setAlignment(Qt.AlignCenter)
            label.setObjectName("progressLabel")
            progress_layout.addWidget(label, 0, Qt.AlignCenter)
            CropAppWindow.progress_labels[element] = label
            if i < len(CropAppWindow.hud_elements) - 1:
                arrow = QLabel("→")
                arrow.setObjectName("progressArrow")
                progress_layout.addWidget(arrow, 0, Qt.AlignCenter)
        progress_layout.addStretch()
        CropAppWindow.progress_bar = QProgressBar()
        wizard_layout.addWidget(CropAppWindow.progress_bar)
        CropAppWindow.view_stack = QStackedWidget()
        left_pane_layout.addWidget(CropAppWindow.view_stack, 1)
        CropAppWindow.video_frame = QWidget()
        CropAppWindow.video_frame.setObjectName("videoFrame")
        CropAppWindow.view_stack.addWidget(CropAppWindow.video_frame)
        CropAppWindow.draw_scroll_area = QScrollArea()
        CropAppWindow.draw_scroll_area.setObjectName("drawScrollArea")
        CropAppWindow.draw_widget = DrawWidget()
        CropAppWindow.draw_scroll_area.setWidget(CropAppWindow.draw_widget)
        CropAppWindow.draw_scroll_area.setWidgetResizable(True)
        CropAppWindow.draw_scroll_area.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        CropAppWindow.draw_scroll_area.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        CropAppWindow.draw_scroll_area.setFrameShape(QFrame.NoFrame)
        CropAppWindow.draw_widget.set_scroll_area(CropAppWindow.draw_scroll_area)
        CropAppWindow.view_stack.addWidget(CropAppWindow.draw_scroll_area)
        slider_container = QFrame()
        slider_container.setObjectName("sliderContainer")
        left_pane_layout.addWidget(slider_container)
        slider_layout = QHBoxLayout(slider_container)
        slider_layout.setContentsMargins(10, 5, 10, 5)
        slider_layout.setSpacing(10)
        CropAppWindow.position_slider = QSlider(Qt.Horizontal)
        CropAppWindow.position_slider.setRange(0, 1000)
        CropAppWindow.position_slider.setEnabled(False)
        CropAppWindow.current_time_label = QLabel("00:00")
        CropAppWindow.current_time_label.setAlignment(Qt.AlignCenter)
        CropAppWindow.total_time_label = QLabel("00:00")
        CropAppWindow.total_time_label.setAlignment(Qt.AlignCenter)
        slider_layout.addWidget(CropAppWindow.current_time_label)
        slider_layout.addWidget(CropAppWindow.position_slider, 1)
        slider_layout.addWidget(CropAppWindow.total_time_label)
        CropAppWindow.controls_frame = QFrame()
        CropAppWindow.controls_frame.setObjectName("controlsFrame")
        left_pane_layout.addWidget(CropAppWindow.controls_frame)
        controls_layout = QHBoxLayout(CropAppWindow.controls_frame)
        controls_layout.setSpacing(20)
        CropAppWindow.open_button = QPushButton("UPLOAD VIDEO")
        CropAppWindow.snapshot_button = QPushButton("START CROPPING")
        CropAppWindow.magic_wand_button = QPushButton("🪄 MAGIC WAND")
        CropAppWindow.play_pause_button = QPushButton("▶ PLAY")
        CropAppWindow.return_button = QPushButton("RETURN TO MAIN APP")
        CropAppWindow.reset_state_button = QPushButton("RESET ALL")
        left_controls = QHBoxLayout()
        left_controls.setSpacing(10)
        left_controls.addWidget(CropAppWindow.open_button)
        left_controls.addWidget(CropAppWindow.snapshot_button)
        left_controls.addWidget(CropAppWindow.magic_wand_button)
        right_controls = QHBoxLayout()
        right_controls.setSpacing(10)
        right_controls.addWidget(CropAppWindow.return_button)
        right_controls.addWidget(CropAppWindow.reset_state_button)
        controls_layout.addLayout(left_controls)
        controls_layout.addStretch(1)
        controls_layout.addWidget(CropAppWindow.play_pause_button)
        controls_layout.addStretch(1)
        controls_layout.addLayout(right_controls)
        right_pane_widget = QFrame()
        right_pane_widget.setObjectName("portraitPane")
        right_pane_layout = QVBoxLayout(right_pane_widget)
        right_pane_layout.setContentsMargins(0, 0, 0, 0)
        right_pane_layout.setSpacing(0)
        portrait_header = QFrame()
        portrait_header.setObjectName("portraitHeader")
        right_pane_layout.addWidget(portrait_header)
        portrait_header_layout = QHBoxLayout(portrait_header)
        CropAppWindow.status_label = QLabel("Portrait Composer")
        CropAppWindow.status_label.setAlignment(Qt.AlignCenter)
        CropAppWindow.show_placeholders_checkbox = QCheckBox("Show Existing Elements")
        CropAppWindow.show_placeholders_checkbox.setChecked(False)
        CropAppWindow.done_button = QPushButton("FINISH & SAVE")
        portrait_header_layout.addWidget(CropAppWindow.status_label)
        portrait_header_layout.addStretch()
        portrait_header_layout.addWidget(CropAppWindow.show_placeholders_checkbox)
        portrait_header_layout.addWidget(CropAppWindow.done_button)
        CropAppWindow.portrait_scene = QGraphicsScene(CropAppWindow)
        CropAppWindow.portrait_scene.setSceneRect(0, 0, UI_LAYOUT.PORTRAIT_BASE_WIDTH, UI_LAYOUT.PORTRAIT_BASE_HEIGHT)
        CropAppWindow.portrait_scene.setBackgroundBrush(QColor(UI_COLORS.BACKGROUND_DARK))
        CropAppWindow.portrait_view = PortraitView(CropAppWindow.portrait_scene)
        right_pane_layout.addWidget(CropAppWindow.portrait_view, 1)
        portrait_footer = QFrame()
        portrait_footer.setObjectName("portraitFooter")
        right_pane_layout.addWidget(portrait_footer)
        portrait_footer_layout = QHBoxLayout(portrait_footer)
        CropAppWindow.delete_button = QPushButton("DELETE")
        CropAppWindow.undo_button = QPushButton("UNDO")
        CropAppWindow.redo_button = QPushButton("REDO")
        portrait_footer_layout.addStretch()
        portrait_footer_layout.addWidget(CropAppWindow.delete_button)
        portrait_footer_layout.addWidget(CropAppWindow.undo_button)
        portrait_footer_layout.addWidget(CropAppWindow.redo_button)
        portrait_footer_layout.addStretch()
        splitter.addWidget(left_pane_widget)
        splitter.addWidget(right_pane_widget)
        splitter.setSizes([1000, 800])
        self.setup_styles(CropAppWindow)

    def setup_styles(self, CropAppWindow):
        CropAppWindow.setStyleSheet(UNIFIED_STYLESHEET)
        CropAppWindow.setObjectName("CropAppWindow")
        CropAppWindow.open_button.setProperty('class', 'primary large')
        CropAppWindow.snapshot_button.setProperty('class', 'accent')
        CropAppWindow.magic_wand_button.setProperty('class', 'primary')
        CropAppWindow.play_pause_button.setProperty('class', '')
        CropAppWindow.return_button.setProperty('class', 'warning')
        CropAppWindow.reset_state_button.setProperty('class', 'danger')
        CropAppWindow.done_button.setProperty('class', 'success')
        CropAppWindow.delete_button.setProperty('class', 'danger')
        CropAppWindow.undo_button.setProperty('class', 'primary')
        CropAppWindow.redo_button.setProperty('class', 'primary')
        for btn in [CropAppWindow.open_button, CropAppWindow.snapshot_button, CropAppWindow.magic_wand_button,
                    CropAppWindow.play_pause_button, CropAppWindow.return_button, CropAppWindow.reset_state_button,
                    CropAppWindow.done_button, CropAppWindow.delete_button, CropAppWindow.undo_button, CropAppWindow.redo_button]:
            btn.style().unpolish(btn)
            btn.style().polish(btn)