import sys
import os
sys.dont_write_bytecode = True
os.environ['PYTHONDONTWRITEBYTECODE'] = '1'
os.environ['PYTHONPYCACHEPREFIX'] = os.path.join(os.path.expanduser('~'), '.null_cache_dir')

from PyQt5.QtGui import QColor, QCursor, QBrush
from PyQt5.QtWidgets import (
    QWidget, QPushButton, QHBoxLayout, QVBoxLayout,
    QLabel, QSlider, QStackedWidget, QFrame, QProgressBar, QScrollArea, QSplitter, QCheckBox, QGraphicsScene
)

from PyQt5.QtCore import Qt
from crop_widgets import DrawWidget, SeekSlider, UploadOverlay
from config import HUD_ELEMENT_MAPPINGS, UNIFIED_STYLESHEET, UI_LAYOUT, UI_COLORS
from portrait_view import PortraitView

class AspectRatioWidget(QWidget):
    """Enforces a specific aspect ratio for its content while remaining optionally centered."""

    def __init__(self, widget, ratio=16/9, alignment=Qt.AlignCenter, parent=None):
        super().__init__(parent)
        self.ratio = ratio
        self.content_widget = widget
        self.setAttribute(Qt.WA_TranslucentBackground)
        layout = QVBoxLayout(self)
        layout.setContentsMargins(0, 0, 0, 0)
        layout.setSpacing(0)
        layout.setAlignment(alignment)
        layout.addWidget(widget)

    def set_ratio(self, ratio):
        self.ratio = ratio
        self.resizeEvent(None)

    def resizeEvent(self, event):
        size = event.size() if event else self.size()
        w, h = size.width(), size.height()
        if h == 0: return
        if w / h > self.ratio:
            new_w = int(h * self.ratio)
            self.content_widget.setFixedSize(new_w, h)
        else:
            new_h = int(w / self.ratio)
            self.content_widget.setFixedSize(w, new_h)
        self.content_widget.update()
        if event: super().resizeEvent(event)

class Ui_CropApp:
    def setupUi(self, CropAppWindow):
        CropAppWindow.setWindowTitle("Fortnite Crop Tool")
        CropAppWindow.resize(1800, 930)
        CropAppWindow.setMinimumSize(1250, 650)
        main_layout = QHBoxLayout(CropAppWindow)
        main_layout.setContentsMargins(0, 0, 0, 0)
        main_layout.setSpacing(0)
        left_pane_widget = QFrame()
        left_pane_layout = QVBoxLayout(left_pane_widget)
        left_pane_layout.setContentsMargins(0, 0, 0, 0)
        left_pane_layout.setSpacing(0)
        CropAppWindow.wizard_frame = QFrame()
        CropAppWindow.wizard_frame.setObjectName("wizardFrame")
        left_pane_layout.addWidget(CropAppWindow.wizard_frame)
        wizard_layout = QVBoxLayout(CropAppWindow.wizard_frame)
        wizard_layout.setContentsMargins(20, 12, 20, 12)
        wizard_layout.setSpacing(8)
        CropAppWindow.progress_bar = QProgressBar()
        CropAppWindow.progress_bar.setFixedHeight(UI_LAYOUT.PROGRESS_BAR_HEIGHT)
        CropAppWindow.progress_bar.setVisible(False)
        wizard_layout.addWidget(CropAppWindow.progress_bar)
        CropAppWindow.goal_label = QLabel("")
        CropAppWindow.goal_label.setVisible(True)
        CropAppWindow.goal_label.setStyleSheet(f"color: {UI_COLORS.TEXT_SECONDARY}; font-size: 12px; font-weight: 700;")
        wizard_layout.addWidget(CropAppWindow.goal_label)
        CropAppWindow.status_label = QLabel("")
        CropAppWindow.status_label.setVisible(True)
        CropAppWindow.status_label.setStyleSheet(f"color: {UI_COLORS.TEXT_DISABLED}; font-size: 11px;")
        wizard_layout.addWidget(CropAppWindow.status_label)
        wizard_layout.addStretch(1)
        CropAppWindow.hud_elements = list(HUD_ELEMENT_MAPPINGS.values())
        CropAppWindow.view_stack = QStackedWidget()
        left_pane_layout.addWidget(CropAppWindow.view_stack, 1)

        from PyQt5.QtWidgets import QStackedLayout
        CropAppWindow.video_frame = QWidget()
        CropAppWindow.video_frame.setObjectName("videoFrame")
        CropAppWindow.video_stack = QStackedLayout(CropAppWindow.video_frame)
        CropAppWindow.video_stack.setStackingMode(QStackedLayout.StackAll)
        CropAppWindow.video_viewport_container = QWidget()
        CropAppWindow.video_viewport_container.setContentsMargins(0, 0, 0, 0)
        _center_row = QHBoxLayout(CropAppWindow.video_viewport_container)
        _center_row.setContentsMargins(0, 0, 0, 0)
        _center_row.setSpacing(0)
        CropAppWindow.video_surface = QWidget()
        CropAppWindow.video_surface.setAttribute(Qt.WA_NativeWindow)
        CropAppWindow.video_surface.setAttribute(Qt.WA_OpaquePaintEvent)
        CropAppWindow.video_surface.setAttribute(Qt.WA_PaintOnScreen)
        CropAppWindow.video_ratio_container = AspectRatioWidget(CropAppWindow.video_surface, 16/9)
        _center_row.addWidget(CropAppWindow.video_ratio_container)
        CropAppWindow.video_stack.addWidget(CropAppWindow.video_viewport_container)
        CropAppWindow.view_stack.addWidget(CropAppWindow.video_frame)
        CropAppWindow.mpv_error_label = QLabel("⚠️ MPV ENGINE NOT FOUND\nPlayback disabled. Please ensure 64-bit libmpv-2.dll is in 'binaries' folder.")
        CropAppWindow.mpv_error_label.setStyleSheet("color: #ff4d4d; font-weight: bold; font-size: 16px; background: rgba(0,0,0,180); padding: 20px; border-radius: 10px;")
        CropAppWindow.mpv_error_label.setAlignment(Qt.AlignCenter)
        CropAppWindow.mpv_error_label.setVisible(False)
        CropAppWindow.video_stack.addWidget(CropAppWindow.mpv_error_label)
        CropAppWindow.shortcuts_label = QLabel("Hotkeys: [Del] Delete  |  [Arrows] Nudge/Seek  |  [Space] Play/Pause  |  [Ctrl+Z] Undo")
        CropAppWindow.shortcuts_label.setStyleSheet(f"color: {UI_COLORS.TEXT_DISABLED}; font-size: 10px; padding: 2px;")
        CropAppWindow.shortcuts_label.setAlignment(Qt.AlignRight)
        CropAppWindow.draw_scroll_area = QScrollArea()
        CropAppWindow.draw_scroll_area.setObjectName("drawScrollArea")
        CropAppWindow.draw_widget = DrawWidget()
        CropAppWindow.draw_scroll_area.setWidget(CropAppWindow.draw_widget)
        CropAppWindow.draw_scroll_area.setWidgetResizable(True)
        CropAppWindow.draw_scroll_area.setAlignment(Qt.AlignCenter)
        CropAppWindow.draw_scroll_area.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        CropAppWindow.draw_scroll_area.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        CropAppWindow.draw_scroll_area.setFrameShape(QFrame.NoFrame)
        corner = QWidget()
        corner.setStyleSheet("background: transparent;")
        CropAppWindow.draw_scroll_area.setCornerWidget(corner)
        CropAppWindow.draw_widget.set_scroll_area(CropAppWindow.draw_scroll_area)
        CropAppWindow.draw_refine_hint_container = QFrame(CropAppWindow.draw_scroll_area.viewport())
        CropAppWindow.draw_refine_hint_container.setObjectName("uploadHintContainer")
        draw_hint_layout = QVBoxLayout(CropAppWindow.draw_refine_hint_container)
        draw_hint_layout.setContentsMargins(18, 12, 18, 12)
        draw_hint_layout.setSpacing(0)
        CropAppWindow.draw_refine_hint_label = QLabel(
            "Now, please refine selection.\n(Use the small arrows to adjust the HUD shape)"
        )
        CropAppWindow.draw_refine_hint_label.setObjectName("uploadHintLabel")
        CropAppWindow.draw_refine_hint_label.setWordWrap(True)
        CropAppWindow.draw_refine_hint_label.setAlignment(Qt.AlignCenter)
        draw_hint_layout.addWidget(CropAppWindow.draw_refine_hint_label)
        CropAppWindow.draw_refine_hint_container.setVisible(False)
        CropAppWindow.view_stack.addWidget(CropAppWindow.draw_scroll_area)
        CropAppWindow.slider_container = QFrame()
        CropAppWindow.slider_container.setObjectName("sliderContainer")
        left_pane_layout.addWidget(CropAppWindow.slider_container)
        slider_layout = QHBoxLayout(CropAppWindow.slider_container)
        slider_layout.setContentsMargins(10, 4, 10, 4)
        slider_layout.setSpacing(12)
        CropAppWindow.position_slider = SeekSlider(Qt.Horizontal)
        CropAppWindow.position_slider.setRange(0, 1000)
        CropAppWindow.position_slider.setEnabled(False)
        CropAppWindow.position_slider.setToolTip("Slide this bar to move through the video.")
        CropAppWindow.current_time_label = QLabel("00:00")
        CropAppWindow.current_time_label.setAlignment(Qt.AlignCenter)
        CropAppWindow.total_time_label = QLabel("00:00")
        CropAppWindow.total_time_label.setAlignment(Qt.AlignCenter)
        slider_layout.addWidget(CropAppWindow.current_time_label)
        slider_layout.addWidget(CropAppWindow.position_slider, 1)
        slider_layout.addWidget(CropAppWindow.total_time_label)
        CropAppWindow.controls_frame = QFrame()
        CropAppWindow.controls_frame.setObjectName("controlsFrame")
        CropAppWindow.controls_frame.setFixedHeight(50)
        left_pane_layout.addWidget(CropAppWindow.controls_frame)
        controls_layout = QHBoxLayout(CropAppWindow.controls_frame)
        controls_layout.setContentsMargins(10, 0, 10, 0)
        controls_layout.setSpacing(30)
        CropAppWindow.open_button = QPushButton("UPLOAD VIDEO")
        CropAppWindow.open_button.setToolTip("Click here to pick a video from your computer.")
        CropAppWindow.upload_overlay = UploadOverlay(CropAppWindow.open_button, CropAppWindow.video_frame, CropAppWindow)
        CropAppWindow.upload_overlay.show()
        CropAppWindow.snapshot_button = QPushButton("START CROPPING")
        CropAppWindow.snapshot_button.setToolTip("Take a picture of this frame so you can start drawing boxes.")
        CropAppWindow.cropping_hint_overlay = UploadOverlay(CropAppWindow.snapshot_button, CropAppWindow.video_frame, CropAppWindow, "Click \"START CROPPING\" When Ready!")
        CropAppWindow.cropping_hint_overlay.hide()
        CropAppWindow.magic_wand_button = QPushButton("🪄 MAGIC WAND")
        CropAppWindow.magic_wand_button.setToolTip("Let the computer try to find the HUD items for you automatically.")
        CropAppWindow.play_pause_button = QPushButton("▶ PLAY")
        CropAppWindow.play_pause_button.setToolTip("Play or pause the video.")
        CropAppWindow.play_pause_button.setFixedSize(110, UI_LAYOUT.PORTRAIT_BUTTON_HEIGHT)
        CropAppWindow.return_button = QPushButton("RETURN TO MAIN APP")
        CropAppWindow.return_button.setToolTip("Close this tool and go back to the main menu.")
        CropAppWindow.reset_state_button = QPushButton("RESET ALL")
        CropAppWindow.reset_state_button.setToolTip("Wipe everything clean and start over from scratch.")
        left_controls = QHBoxLayout()
        left_controls.setContentsMargins(0, 0, 0, 0)
        left_controls.setSpacing(20)
        left_controls.addWidget(CropAppWindow.open_button)
        left_controls.addWidget(CropAppWindow.snapshot_button)
        left_controls.addWidget(CropAppWindow.magic_wand_button)
        right_controls = QHBoxLayout()
        right_controls.setContentsMargins(0, 0, 0, 0)
        right_controls.setSpacing(20)
        CropAppWindow.back_to_video_button = QPushButton("⬅ BACK TO VIDEO")
        CropAppWindow.back_to_video_button.setToolTip("Stop drawing and go back to the video seeker.")
        CropAppWindow.back_to_video_button.setVisible(False)
        CropAppWindow.back_to_video_button.setProperty('class', 'warning')
        right_controls.addWidget(CropAppWindow.back_to_video_button)
        right_controls.addWidget(CropAppWindow.return_button)
        right_controls.addWidget(CropAppWindow.reset_state_button)
        controls_layout.addLayout(left_controls)
        controls_layout.addStretch(1)
        controls_layout.addWidget(CropAppWindow.play_pause_button, 0, Qt.AlignVCenter)
        controls_layout.addStretch(1)
        controls_layout.addLayout(right_controls)
        right_pane_widget = QFrame()
        right_pane_widget.setObjectName("rightPane")
        right_pane_widget.setMinimumWidth(600)
        right_pane_layout = QVBoxLayout(right_pane_widget)
        right_pane_layout.setContentsMargins(0, 0, 0, 0)
        right_pane_layout.setSpacing(0)
        portrait_header = QFrame()
        portrait_header.setObjectName("portraitHeader")
        right_pane_layout.addWidget(portrait_header)
        portrait_header_layout = QHBoxLayout(portrait_header)
        portrait_header_layout.setContentsMargins(10, 4, 10, 4)
        portrait_header_layout.setSpacing(12)
        CropAppWindow.snap_toggle_button = QPushButton("🧲 SNAP")
        CropAppWindow.snap_toggle_button.setCheckable(True)
        CropAppWindow.snap_toggle_button.setChecked(True)
        CropAppWindow.snap_toggle_button.setToolTip("Turn the 'Magnetic Pull' on or off. Blue lines will always help you align things.")
        CropAppWindow.transparency_slider = QSlider(Qt.Horizontal)
        CropAppWindow.transparency_slider.setProperty('class', 'portrait-sld')
        CropAppWindow.transparency_slider.setRange(20, 255)
        CropAppWindow.transparency_slider.setValue(UI_COLORS.OPACITY_PH_ALPHA)
        CropAppWindow.transparency_slider.setFixedWidth(UI_LAYOUT.PORTRAIT_SLIDER_WIDTH)
        CropAppWindow.transparency_slider.setFixedHeight(25)
        CropAppWindow.transparency_slider.setContentsMargins(0, 0, 0, 0)
        CropAppWindow.transparency_slider.setToolTip("Make old saved crops look see-through or solid.")
        CropAppWindow.show_placeholders_checkbox = QCheckBox("Show Existing Crops")
        CropAppWindow.show_placeholders_checkbox.setProperty('class', 'portrait-chk')
        CropAppWindow.show_placeholders_checkbox.setCursor(Qt.PointingHandCursor)
        CropAppWindow.show_placeholders_checkbox.setChecked(False)
        CropAppWindow.show_placeholders_checkbox.setToolTip("Show or hide the crops you saved in the past.")
        CropAppWindow.done_button = QPushButton("FINISH && SAVE")
        CropAppWindow.done_button.setToolTip("Save all your work permanently to the computer.")
        portrait_header_layout.addWidget(CropAppWindow.show_placeholders_checkbox)
        portrait_header_layout.addWidget(CropAppWindow.transparency_slider)
        portrait_header_layout.addStretch()
        portrait_header_layout.addWidget(CropAppWindow.snap_toggle_button)
        portrait_header_layout.addSpacing(50)
        portrait_header_layout.addWidget(CropAppWindow.done_button)
        portrait_header_layout.addSpacing(75)
        CropAppWindow.portrait_scene = QGraphicsScene(CropAppWindow)
        CropAppWindow.portrait_scene.setSceneRect(0, 0, UI_LAYOUT.PORTRAIT_BASE_WIDTH, UI_LAYOUT.PORTRAIT_BASE_HEIGHT)
        CropAppWindow.portrait_scene.setBackgroundBrush(QBrush(QColor("#111827")))
        CropAppWindow.portrait_view = PortraitView(CropAppWindow.portrait_scene)
        CropAppWindow.portrait_view.setFrameShape(QFrame.NoFrame)
        CropAppWindow.portrait_view.setBackgroundBrush(QBrush(QColor("#111827")))
        CropAppWindow.portrait_view.setStyleSheet("background: #111827; border: none;")
        middle_row_widget = QWidget()
        middle_row_layout = QHBoxLayout(middle_row_widget)
        middle_row_layout.setContentsMargins(0, 0, 0, 0)
        middle_row_layout.setSpacing(0)
        portrait_ratio_container = AspectRatioWidget(CropAppWindow.portrait_view, 9/16, Qt.AlignRight)
        middle_row_layout.addWidget(portrait_ratio_container, 1)
        undo_redo_container = QWidget()
        CropAppWindow.undo_button = QPushButton("UNDO")
        CropAppWindow.undo_button.setToolTip("Go back one step if you made a mistake.")
        CropAppWindow.undo_button.setFixedWidth(60)
        CropAppWindow.redo_button = QPushButton("REDO")
        CropAppWindow.redo_button.setToolTip("Forward one step if you undo too much.")
        CropAppWindow.redo_button.setFixedWidth(60)
        undo_redo_container.setFixedWidth(100) 
        ur_outer_layout = QHBoxLayout(undo_redo_container)
        ur_outer_layout.setContentsMargins(20, 0, 20, 0)
        undo_redo_vbox = QVBoxLayout()
        undo_redo_vbox.setSpacing(40)
        undo_redo_vbox.setAlignment(Qt.AlignCenter)
        undo_redo_vbox.addWidget(CropAppWindow.undo_button)
        undo_redo_vbox.addWidget(CropAppWindow.redo_button)
        ur_outer_layout.addLayout(undo_redo_vbox)
        middle_row_layout.addWidget(undo_redo_container)
        right_pane_layout.addWidget(middle_row_widget, 1)
        portrait_footer = QFrame()
        portrait_footer.setObjectName("portraitFooter")
        right_pane_layout.addWidget(portrait_footer)
        portrait_footer_layout = QHBoxLayout(portrait_footer)
        portrait_footer_layout.setContentsMargins(10, 4, 10, 14)
        portrait_footer_layout.setSpacing(30)
        CropAppWindow.delete_button = QPushButton("DELETE")
        CropAppWindow.delete_button.setToolTip("Remove the selected item from the screen.")
        CropAppWindow.raise_button = QPushButton("")
        CropAppWindow.raise_button.setToolTip("Bring this item to the front so it sits on top of others.")
        raise_layout = QHBoxLayout(CropAppWindow.raise_button)
        raise_layout.setContentsMargins(0, 0, 0, 0)
        raise_label = QLabel('<span style="font-size: 14px;">↑</span>&nbsp;&nbsp;<span style="font-size: 9px;">UP ONE LEVEL</span>&nbsp;&nbsp;<span style="font-size: 14px;">↑</span>')
        raise_label.setAlignment(Qt.AlignCenter)
        raise_label.setAttribute(Qt.WA_TransparentForMouseEvents)
        raise_label.setStyleSheet("background: transparent; border: none; color: white;")
        raise_layout.addWidget(raise_label)
        CropAppWindow.lower_button = QPushButton("")
        CropAppWindow.lower_button.setToolTip("Send this item to the back so it sits behind others.")
        lower_layout = QHBoxLayout(CropAppWindow.lower_button)
        lower_layout.setContentsMargins(0, 0, 0, 0)
        lower_label = QLabel('<span style="font-size: 14px;">↓</span>&nbsp;&nbsp;<span style="font-size: 9px;">DOWN ONE LEVEL</span>&nbsp;&nbsp;<span style="font-size: 14px;">↓</span>')
        lower_label.setAlignment(Qt.AlignCenter)
        lower_label.setAttribute(Qt.WA_TransparentForMouseEvents)
        lower_label.setStyleSheet("background: transparent; border: none; color: white;")
        lower_layout.addWidget(lower_label)
        portrait_footer_layout.addStretch()
        portrait_footer_layout.addWidget(CropAppWindow.lower_button)
        portrait_footer_layout.addWidget(CropAppWindow.delete_button)
        portrait_footer_layout.addWidget(CropAppWindow.raise_button)
        portrait_footer_layout.addStretch()
        central_divider = QFrame()
        central_divider.setObjectName("centralDivider")
        central_divider.setFixedWidth(18)
        main_layout.addWidget(left_pane_widget, 1174)
        main_layout.addWidget(central_divider)
        main_layout.addWidget(right_pane_widget, 626)
        CropAppWindow.magic_wand_button.setVisible(False)
        CropAppWindow.snapshot_button.setEnabled(False)
        CropAppWindow.play_pause_button.setEnabled(False)
        CropAppWindow.done_button.setEnabled(False)
        CropAppWindow.delete_button.setEnabled(False)
        CropAppWindow.undo_button.setEnabled(False)
        CropAppWindow.redo_button.setEnabled(False)
        CropAppWindow.snap_toggle_button.setEnabled(False)
        CropAppWindow.reset_state_button.setEnabled(False)
        CropAppWindow.show_placeholders_checkbox.setEnabled(True)
        CropAppWindow.transparency_slider.setEnabled(False)
        CropAppWindow.transparency_slider.setVisible(False)
        self.setup_styles(CropAppWindow)

    def setup_styles(self, CropAppWindow):
        CropAppWindow.setStyleSheet(UNIFIED_STYLESHEET)
        CropAppWindow.setObjectName("CropAppWindow")
        CropAppWindow.open_button.setProperty('class', 'primary')
        CropAppWindow.snapshot_button.setProperty('class', 'accent')
        CropAppWindow.magic_wand_button.setProperty('class', 'primary')
        CropAppWindow.play_pause_button.setProperty('class', '')
        CropAppWindow.back_to_video_button.setProperty('class', 'primary') 
        CropAppWindow.return_button.setProperty('class', 'teal-btn')
        CropAppWindow.reset_state_button.setProperty('class', 'danger')
        CropAppWindow.done_button.setProperty('class', 'success portrait-btn')
        CropAppWindow.delete_button.setProperty('class', 'danger portrait-btn')
        CropAppWindow.undo_button.setProperty('class', 'primary portrait-btn')
        CropAppWindow.redo_button.setProperty('class', 'primary portrait-btn')
        CropAppWindow.raise_button.setProperty('class', 'primary portrait-btn')
        CropAppWindow.lower_button.setProperty('class', 'primary portrait-btn')
        CropAppWindow.snap_toggle_button.setProperty('class', 'primary portrait-btn')
        portrait_btns = [
            CropAppWindow.done_button, CropAppWindow.delete_button, CropAppWindow.undo_button,
            CropAppWindow.redo_button, CropAppWindow.raise_button, CropAppWindow.lower_button,
            CropAppWindow.snap_toggle_button, CropAppWindow.show_placeholders_checkbox,
            CropAppWindow.transparency_slider
        ]
        for btn in [CropAppWindow.open_button, CropAppWindow.snapshot_button, CropAppWindow.magic_wand_button,
                    CropAppWindow.play_pause_button, CropAppWindow.back_to_video_button, CropAppWindow.return_button, CropAppWindow.reset_state_button,
                    CropAppWindow.done_button, CropAppWindow.delete_button, CropAppWindow.undo_button, CropAppWindow.redo_button,
                    CropAppWindow.snap_toggle_button, CropAppWindow.raise_button, CropAppWindow.lower_button,
                    CropAppWindow.show_placeholders_checkbox, CropAppWindow.transparency_slider]:
            if not isinstance(btn, (QCheckBox, QSlider)):
                if btn is CropAppWindow.play_pause_button:
                    btn.setFixedSize(110, UI_LAYOUT.PORTRAIT_BUTTON_HEIGHT)
                else:
                    btn.setFixedHeight(UI_LAYOUT.PORTRAIT_BUTTON_HEIGHT)
            if btn in [CropAppWindow.raise_button, CropAppWindow.lower_button]:
                btn.setFixedWidth(125)
            btn.setCursor(Qt.PointingHandCursor)
            btn.setFocusPolicy(Qt.NoFocus)
            btn.style().unpolish(btn)
            btn.style().polish(btn)
        
