from PyQt5.QtWidgets import (
    QWidget, QVBoxLayout, QHBoxLayout, QLabel, QPushButton, QSizePolicy
)

from PyQt5.QtCore import Qt
from utilities.merger_ui_widgets import MergerUIWidgetsMixin

class MergerUIBuildMixin(MergerUIWidgetsMixin):
    def setup_ui(self):
        root = QWidget(self.parent)
        self.parent.setCentralWidget(root)
        outer = QVBoxLayout(root)
        outer.setContentsMargins(20, 16, 20, 16)
        outer.setSpacing(16)
        title = QLabel('Sort the Videos in the Correct Desired Order. Hit the "Merge Videos" Button When Done.')
        title.setObjectName("titleLabel")
        title.setAlignment(Qt.AlignHCenter)
        title.setSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        outer.addWidget(title)
        list_container = QHBoxLayout()
        list_container.setContentsMargins(0, 0, 0, 0)
        list_container.setSpacing(8)
        outer.addLayout(list_container, 1)
        list_container.addStretch(1)
        self.parent.listw = self.parent.create_draggable_list_widget()
        self.parent.listw.setMinimumWidth(850)
        self.parent.listw.setMaximumWidth(850)
        self.parent.listw.setSizePolicy(QSizePolicy.Fixed, QSizePolicy.Expanding)
        list_container.addWidget(self.parent.listw, 0)
        move_buttons_layout = self.create_move_buttons()
        move_buttons_layout.setContentsMargins(0, 0, 0, 0)
        list_container.addLayout(move_buttons_layout, 0)
        list_container.addStretch(1)
        bottom_band = self.create_bottom_band()
        bottom_band.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        outer.addWidget(bottom_band, 0)
        self.parent.status_label = QLabel("Ready. Add 2 to 100 videos to begin.")
        self.parent.status_label.setStyleSheet("color: #7289da; font-weight: bold;")
        self.parent.status_label.setSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        self.parent.status_label.setAlignment(Qt.AlignCenter)
        outer.addWidget(self.parent.status_label, 0)
        merge_row = self.create_merge_row()
        merge_row.setSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        outer.addWidget(merge_row, 0)
        outer.setStretch(0, 0)
        outer.setStretch(1, 1)
        outer.setStretch(2, 0)
        outer.setStretch(3, 0)
        outer.setStretch(4, 0)

    def create_move_buttons(self):
        col = QVBoxLayout()
        col.setContentsMargins(0, 0, 0, 0)
        col.setSpacing(20)
        self.parent.btn_up = QPushButton("▲ Up ▲")
        self.parent.btn_up.setToolTip("Move selected video up")
        self.parent.btn_up.setSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        self.parent.btn_up.setFixedSize(87, 43)
        self.parent.btn_up.setProperty("class", "move-btn")
        self.parent.btn_up.setCursor(Qt.PointingHandCursor)
        self.parent.btn_up.clicked.connect(lambda: self.parent.move_item(-1))
        self.parent.btn_down = QPushButton("▼ Down ▼")
        self.parent.btn_down.setToolTip("Move selected video down")
        self.parent.btn_down.setSizePolicy(QSizePolicy.Fixed, QSizePolicy.Fixed)
        self.parent.btn_down.setFixedSize(87, 43)
        self.parent.btn_down.setProperty("class", "move-btn")
        self.parent.btn_down.setCursor(Qt.PointingHandCursor)
        self.parent.btn_down.clicked.connect(lambda: self.parent.move_item(1))
        col.addStretch(1)
        col.addWidget(self.parent.btn_up)
        col.addWidget(self.parent.btn_down)
        col.addStretch(1)
        return col

    def create_bottom_band(self):
        band = QHBoxLayout()
        band.setContentsMargins(0, 0, 0, 0)
        band.setSpacing(0)
        left_wrap = QWidget()
        left_wrap.setLayout(self.create_music_layout())
        center_wrap = QWidget()
        center_wrap.setLayout(self.create_center_buttons())
        band.addStretch(1)
        band.addWidget(center_wrap, 0)
        band.addSpacing(8)
        band.addWidget(left_wrap, 0)
        band.addStretch(1)
        wrap = QWidget()
        wrap.setLayout(band)
        wrap.setSizePolicy(QSizePolicy.Preferred, QSizePolicy.Fixed)
        return wrap